# Example workload and a PodDisruptionBudget
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: gcr.io/google_containers/echoserver:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: echobudget
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: echoserver
